title: Pablo Bendiksen # your name (or website title) here
logo: "/images/pablo_bendiksen.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Interested in building data stories for applications in the social sciences
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/pablo-bendiksen-11b583127/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-000000-0
