title: Pablo Bendiksen # your name (or website title) here
logo: "/images/pablo_bendiksen.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my Portfolio for Data Visualization and Statistical Analyses tasks.
  Selected works are either actual research projects I've done or completed coursework.
  <br><br>
  <a href="https://www.linkedin.com/in/pablo-bendiksen-11b583127/">View My LinkedIn Profile</a>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
